# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('imagem', models.ImageField(blank=True, default='img/cursos/noperfil.png', null=True, upload_to='img/cursos/', verbose_name='Imagem')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Público-alvo',
                'verbose_name_plural': 'Público-alvo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('perfil', models.CharField(max_length=500, verbose_name='Perfil')),
                ('imagem_perfil', models.ImageField(blank=True, default='img/usuarios/noperfil.png', null=True, upload_to='img/usuarios/', verbose_name='Imagem de Perfil')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('residencial', models.CharField(max_length=11, verbose_name='Residêncial')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_curso', to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='inscritos',
            field=models.ManyToManyField(null=True, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='publico',
            field=models.ManyToManyField(to='core.Publico'),
        ),
    ]
