# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscritos',
            field=models.ManyToManyField(blank=True, null=True, to='core.Usuario'),
        ),
    ]
